tweaks/resize: add BTRFS resize option
In advance of the installer being able to select filesystem, this commit
allows the filesystem being resized to be BTRFS.
BTRFS only allows working with the filesystem when mounted and uses the
mountpoint to reference the filesystem. This is why the code is split into
BTRFS and non-BTRFS sections.

d/control: The initscripts previously relied on e2fsprogs and
f2fs-tools, though this was not listed.

diff --git a/common/initramfs-tools/scripts/local-bottom/resize-rootfs b/common/initramfs-tools/scripts/local-bottom/resize-rootfs
--- a/common/initramfs-tools/scripts/local-bottom/resize-rootfs
+++ b/common/initramfs-tools/scripts/local-bottom/resize-rootfs
@@ -24,9 +24,6 @@ done
 plymouth --ping &&
 plymouth message --text="Resizing file system during initial boot"
 
-# There was something to do, unmount and resize
-umount "${rootmnt}" || fail "failed to umount ${rootmnt}";
-
 # this is taken from 'mountroot' function
 #   see /usr/share/initramfs-tools/scripts/local
 if [ -z "${ROOTFSTYPE}" ]; then
@@ -35,19 +32,27 @@ else
     FSTYPE=${ROOTFSTYPE}
 fi
 
-case ${FSTYPE} in
-    f2fs) RESIZE_CMD="/sbin/resize.f2fs";;
-    ext*) RESIZE_CMD="/sbin/resize2fs -f";;
-esac
+if [ ${FSTYPE} = "btrfs" ]; then
+    # BTRFS requires FS to be mounted
+    /bin/btrfs filesystem resize max ${rootmnt} || fail "failed to resize ${ROOT} with fs ${FSTYPE}"
+else
+    # There was something to do, unmount and resize
+    umount "${rootmnt}" || fail "failed to umount ${rootmnt}";
 
-if [ "${RESIZE_CMD}" ]; then
-    ${RESIZE_CMD} ${ROOT} || fail "failed to resize ${ROOT} with fs ${FSTYPE}"
+    case ${FSTYPE} in
+        f2fs) RESIZE_CMD="/sbin/resize.f2fs";;
+        ext*) RESIZE_CMD="/sbin/resize2fs -f";;
+    esac
+
+    if [ "${RESIZE_CMD}" ]; then
+        ${RESIZE_CMD} ${ROOT} || fail "failed to resize ${ROOT} with fs ${FSTYPE}"
+    fi
+
+    roflag="-r"
+    [ "${readonly}" = "y" ] || roflag="-w"
+    mount ${roflag} ${FSTYPE:+-t ${FSTYPE} }${ROOTFLAGS} ${ROOT} ${rootmnt} ||
+        fail "failed to re-mount ${ROOT}. this is bad!"
 fi
-
-roflag="-r"
-[ "${readonly}" = "y" ] || roflag="-w"
-mount ${roflag} ${FSTYPE:+-t ${FSTYPE} }${ROOTFLAGS} ${ROOT} ${rootmnt} ||
-	fail "failed to re-mount ${ROOT}. this is bad!"
 
 touch "${rootmnt}/etc/resized-rootfs"
 
